import { logger } from "./utils/logger.js";
import { createPR, pushBranch } from "./utils/github.js";
import type { WorkerResult, PRResult, LivingRepoConfig, TriagedIssue } from "./types.js";

function buildPRBody(issue: TriagedIssue, result: WorkerResult): string {
  const lines: string[] = [
    `## Summary`,
    ``,
    `Automated fix for **#${issue.issue_id}** — ${issue.title}`,
    ``,
    `**Classification**: ${issue.classification} | **Severity**: ${issue.severity} | **Complexity**: ${issue.complexity}`,
    ``,
    `## Approach`,
    ``,
    issue.approach,
    ``,
    `## Changes`,
    ``,
  ];

  if (result.files_changed.length > 0) {
    for (const f of result.files_changed) {
      lines.push(`- \`${f}\``);
    }
  } else {
    lines.push(`_No files changed._`);
  }

  lines.push(``);
  lines.push(`## Agent Summary`);
  lines.push(``);
  lines.push(result.summary.slice(0, 3000));
  lines.push(``);

  if (result.test_results) {
    lines.push(`## Test Results`);
    lines.push(``);
    lines.push("```");
    lines.push(result.test_results);
    lines.push("```");
    lines.push(``);
  }

  lines.push(`## Metadata`);
  lines.push(``);
  lines.push(`- **Confidence**: ${result.confidence}`);
  lines.push(`- **Generated by**: The Living Repo`);
  lines.push(``);
  lines.push(`---`);
  lines.push(`_This PR was created autonomously by [The Living Repo](https://github.com/living-repo). Review carefully before merging._`);

  return lines.join("\n");
}

export async function submitPR(
  issue: TriagedIssue,
  result: WorkerResult,
  config: LivingRepoConfig,
  worktreePath: string
): Promise<PRResult> {
  logger.info("PR", `Submitting PR for issue #${issue.issue_id}`);

  try {
    await pushBranch(worktreePath, result.branch_name);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error("PR", `Failed to push branch ${result.branch_name}: ${msg}`);
    throw err;
  }

  const title = `${issue.classification === "bug" ? "Fix" : "Implement"}: ${issue.title} (closes #${issue.issue_id})`;
  const body = buildPRBody(issue, result);

  const labels = [
    "living-repo",
    `auto-${issue.classification}`,
    `confidence-${result.confidence}`,
  ];

  const pr = await createPR(config.repoOwner, config.repoName, {
    title,
    body,
    head: result.branch_name,
    labels,
  });

  const prResult: PRResult = {
    issue_id: issue.issue_id,
    pr_number: pr.number,
    pr_url: pr.html_url,
    title,
    status: "open",
    created_at: new Date().toISOString(),
  };

  logger.success("PR", `Created PR #${pr.number}: ${pr.html_url}`);
  return prResult;
}

export async function submitPRsForResults(
  issues: TriagedIssue[],
  results: WorkerResult[],
  config: LivingRepoConfig
): Promise<PRResult[]> {
  const prResults: PRResult[] = [];

  for (const result of results) {
    if (!result.success || result.files_changed.length === 0) {
      logger.warn(
        "PR",
        `Skipping PR for issue #${result.issue_id} — no successful changes`
      );
      continue;
    }

    const issue = issues.find((i) => i.issue_id === result.issue_id);
    if (!issue) {
      logger.error("PR", `No issue found for result #${result.issue_id}`);
      continue;
    }

    try {
      const worktreePath = result.branch_name; // the path where the worktree lived
      const pr = await submitPR(issue, result, config, config.repoPath);
      prResults.push(pr);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error("PR", `Failed to create PR for issue #${result.issue_id}: ${msg}`);
    }
  }

  logger.success("PR", `Submitted ${prResults.length} PRs`);
  return prResults;
}
