import OpenAI from "openai";
import * as fs from "fs";
import * as path from "path";
import { logger } from "./utils/logger.js";
import type { LivingRepoConfig, FeatureProposal } from "./types.js";
import { ProposalSetSchema } from "./types.js";
import type { Directives } from "./types.js";

let openai: OpenAI;

function getOpenAI(apiKey: string): OpenAI {
  if (!openai) {
    openai = new OpenAI({ apiKey });
  }
  return openai;
}

const PROPOSER_SYSTEM_PROMPT = `You are a creative product engineer analyzing a GitHub repository to propose ONE valuable new feature.

Analyze the repository's README, existing features, code structure, and open issues to identify the single highest-impact opportunity.

Provide:
- title: concise feature name (imperative, e.g. "Add rate limiting middleware")
- description: what the feature does (2-3 sentences)
- user_benefit: why users would want this (1-2 sentences)
- complexity: S (1 file), M (2-5 files), L (6+ files)
- implementation_sketch: high-level plan (3-5 bullet points)
- priority_score: 1-10 based on impact vs effort

Prioritize features that:
- Solve common pain points visible in issues
- Are feasible for an automated agent to build
- Have clear, testable acceptance criteria
- Don't require external service integrations (unless specified)

Return a JSON object with a "proposals" array containing exactly 1 proposal.`;

export async function generateProposals(
  config: LivingRepoConfig,
  repoContext: string,
  directives?: Directives
): Promise<FeatureProposal[]> {
  const ai = getOpenAI(config.openaiApiKey);

  let userPrompt = `Analyze this repository and propose new features:\n\n${repoContext}`;

  if (directives?.feature_guidance?.length) {
    userPrompt += `\n\n## Feature Guidance from Maintainers\n${directives.feature_guidance.map((g) => `- ${g}`).join("\n")}`;
  }

  logger.info("Proposer", "Generating feature proposals");

  const response = await ai.chat.completions.create({
    model: config.apiModel,
    messages: [
      { role: "system", content: PROPOSER_SYSTEM_PROMPT },
      { role: "user", content: userPrompt },
    ],
    response_format: { type: "json_object" },
    temperature: 0.7,
  });

  const raw = response.choices[0]?.message?.content;
  if (!raw) {
    throw new Error("Empty response from OpenAI for proposals");
  }

  const parsed = ProposalSetSchema.parse(JSON.parse(raw));

  logger.success(
    "Proposer",
    `Generated ${parsed.proposals.length} feature proposals`
  );

  return parsed.proposals;
}

export function buildProposalIssueBody(proposal: FeatureProposal): string {
  const lines = [
    `## Feature Proposal`,
    ``,
    `**Priority**: ${proposal.priority_score}/10 | **Complexity**: ${proposal.complexity}`,
    ``,
    `### Description`,
    ``,
    proposal.description,
    ``,
    `### User Benefit`,
    ``,
    proposal.user_benefit,
    ``,
    `### Implementation Plan`,
    ``,
    proposal.implementation_sketch,
    ``,
    `---`,
    `_This issue was auto-generated by [The Living Repo](https://github.com/living-repo) — an autonomous agent swarm that triages issues, resolves them, and proposes new features._`,
  ];
  return lines.join("\n");
}

export function writeRoadmap(
  repoPath: string,
  proposals: FeatureProposal[]
): string {
  const sorted = [...proposals].sort(
    (a, b) => b.priority_score - a.priority_score
  );

  const lines: string[] = [
    `# ROADMAP.md — Feature Proposals`,
    ``,
    `> Auto-generated by The Living Repo. Review and approve features below.`,
    `> To approve a feature, change its status from \`[ ]\` to \`[x]\`.`,
    `> The agent will build approved features on the next run.`,
    ``,
    `---`,
    ``,
  ];

  for (let i = 0; i < sorted.length; i++) {
    const p = sorted[i];
    lines.push(`## ${i + 1}. [ ] ${p.title}`);
    lines.push(``);
    lines.push(`**Priority**: ${p.priority_score}/10 | **Complexity**: ${p.complexity}`);
    lines.push(``);
    lines.push(`**Description**: ${p.description}`);
    lines.push(``);
    lines.push(`**User Benefit**: ${p.user_benefit}`);
    lines.push(``);
    lines.push(`**Implementation Plan**:`);
    lines.push(p.implementation_sketch);
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  const filePath = path.join(repoPath, "ROADMAP.md");
  fs.writeFileSync(filePath, lines.join("\n"));
  logger.success("Proposer", `Wrote ROADMAP.md with ${sorted.length} proposals`);
  return filePath;
}
